name: Trigger auto deployment for westcoasteducation-app-202307311

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/westcoasteducation-app-202307311-AutoDeployTrigger-9886aa23-f0ac-4745-8929-86a93c526cf5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WESTCOASTEDUCATIONAPP202307311_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.WESTCOASTEDUCATIONAPP202307311_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WESTCOASTEDUCATIONAPP202307311_REGISTRY_PASSWORD }}
          containerAppName: westcoasteducation-app-202307311
          resourceGroup: RG-LABB1-PUB-JG
          imageToBuild: thekingaakk/thekingaakk/westcoasteducation:${{ github.sha }}
          dockerfilePath: Dockerfile

     

